### ISSUE TITLE
应用报大量 “resource pool timed out”，大佬帮分析下原因。

### ISSUE THREAD

**Issue by minxinqing** [XiaoMi/Gaea#101]
昨天应用报大量“SQLSTATE[HY000]: General error: 1105 unknown error: resource pool timed out (SQL: xxxxxxxx”错误，我查看Gaea源码，发现 `resource pool timed out` 错误在 `util\resource_pool.go`的第36行定义。

在这之前的一小段时间应用大量报" SQLSTATE[HY000]: General error: 1105 unknown error: Conn 0: Write(header) failed: write tcp 10.5.1.128:53996->10.0.8.48:3306: write: connection reset by peer (SQL:xxxxxxxxx"错误，在`mysql/conn.go`的402行发现 `Write(header) failed:`定义；与此同时Gaea日志中出现几十条"[shazam_proxy] [nicetuan-middle-payment-prod-002] [NOTICE] [900000001] [main.main.func1:main.go:90] Ignore broken pipe signal"。

重启proxy后，应用恢复正常，而且这些日志只出现在一台应用服务器上（我把应用和proxy部署在同一台机器上），其它7台机器没事。
没弄明白这个问题出现的原因，麻烦大佬帮忙分析下。

**Comment by eastfisher** [comment]
您好. 请问使用的是Gaea哪个版本?

可以先看一下监控中的后端连接数, 是不是达到配置的连接数最大值, 考虑调整连接池参数.

**Comment by minxinqing** [comment]
shazam master分支，5月25日版本，HASH: bac58f40b694140fc778b504a1bce7eec1bd9acd

没有达到配置的连接最大值，配置 capacity:160，max_capacity:200，发生异常那会峰值会话数110.
![image](https://user-images.githubusercontent.com/3809601/91789475-4f8ea800-ec41-11ea-805b-89370e23f543.png)

整个集群只有这一台机器出问题，在mysql链接出问题时，那会redis链接也持续报错小一分钟（猜测那台机器短时间对外连接出了问题），后来redis连接不报错了，mysql用的proxy，报错就一直持续了几个小时，直到重启proxy。

**Comment by minxinqing** [comment]
原因找到了 #106
