### ISSUE TITLE
IsRWSplit判断错误

### ISSUE THREAD

**Issue by makediff** [XiaoMi/Gaea#11]
https://github.com/XiaoMi/Gaea/blob/cf4772269baf22d832aa97e7bb3d4d430bd62b7c/proxy/server/namespace.go#L216

这里应该是
```
return n.userProperties[user].RWSplit == models.ReadWriteSplit
```

**Comment by cx3ptr** [comment]
thanks for your feedback, we will fix it in the next pr.
