### ISSUE TITLE
请教：gaea的web有开源吗？

### ISSUE THREAD

**Issue by tiger7chan** [XiaoMi/Gaea#135]
请教：gaea的web有开源吗？想通过它来查看相关状态

**Comment by chicliz** [comment]
你好, 目前没有哈, 计划最晚在2021年Q1开源

**Comment by tiger7chan** [comment]
哦，好的，谢谢

**Comment by flyonce** [comment]
> 你好, 目前没有哈, 计划最晚在2021年Q1开源

请问，gaea-web模块是否有以开源的版本，谢谢

**Comment by smilethensee** [comment]
> 你好, 目前没有哈, 计划最晚在2021年Q1开源
你好，请问最近有开源计划嘛？
