### ISSUE TITLE
关于gaea后台连接池大小中capacity与maxcapacity疑问

### ISSUE THREAD

**Issue by lulufeiacount** [XiaoMi/Gaea#151]
通过自主测试以及阅读代码并未发现配置中maxcapacity有生效的场景，请问文档中关于连接池大小会在[0,maxCapacity]之间浮动，具体的代码实现是在哪里呢？以下是我看到的目前关于连接池初始化和获取连接池中连接的代码。
        
     rp := &ResourcePool{
		resources:   make(chan resourceWrapper, maxCap),
		factory:     factory,
		available:   sync2.NewAtomicInt64(int64(capacity)),
		capacity:    sync2.NewAtomicInt64(int64(capacity)),
		idleTimeout: sync2.NewAtomicDuration(idleTimeout),
	}
	for i := 0; i < capacity; i++ {
		rp.resources <- resourceWrapper{}
	}

func (rp *ResourcePool) get(ctx context.Context, wait bool) (resource Resource, err error) {
	select {
	case <-ctx.Done():
		return nil, ErrTimeout
	default:
	}

	// Fetch
	var wrapper resourceWrapper
	var ok bool
	select {
	case wrapper, ok = <-rp.resources:
	default:
		if !wait {
			return nil, nil
		}
		startTime := time.Now()
		select {
		case wrapper, ok = <-rp.resources:
		case <-ctx.Done():
			return nil, ErrTimeout
		}
		rp.recordWait(startTime)
	}
	if !ok {
		return nil, ErrClosed
	}

	// Unwrap
	if wrapper.resource == nil {
		wrapper.resource, err = rp.factory() // 实际建立连接
		if err != nil {
			rp.resources <- resourceWrapper{}
			return nil, err
		}
		rp.active.Add(1)
	}
	rp.available.Add(-1)
	rp.inUse.Add(1)
	return wrapper.resource, err
}

连接池是由一个channel进行管理，虽然channel设置的容量为maxcapacity，但是在进行初始化时channel里面的元素数量为capacity，并且后续并未发现channel中放入超过capacity的元素，因此产生了此疑问，烦请解答一二，谢谢。

**Comment by chicliz** [comment]
由于设计问题, maxCapaticy实际没有生效, 如果有需求可以增加capacity的大小.
