### ISSUE TITLE
分表没法和普通单表join查询

### ISSUE THREAD

**Issue by chenshengfu** [XiaoMi/Gaea#173]
分表没法和普通单表join查询，报错提示单表找不到规则，err: rule not found

**Comment by lulufeiacount** [comment]
分片表需要和关联表或者全局表才能进行关联查询

**Comment by chenshengfu** [comment]
意思就是需要把我的普通单表配置为关联表或者全局表是吧？有相关文档吗？

**Comment by chenshengfu** [comment]
意思就是需要把我的普通单表配置为关联表或者全局表是吧？有相关文档吗？

**Comment by lulufeiacount** [comment]
> 意思就是需要把我的普通单表配置为关联表或者全局表是吧？有相关文档吗？

[https://github.com/XiaoMi/Gaea/blob/master/docs/shard.md](url)

关联表和全局表
Gaea分片SQL要求多个表具有关联关系 (一个分片表, 多个关联表), 或者只存在一个分片表, 其余均为全局表.

关联表
关联表需要与同数据库的某个分片表关联. 例如, 将db_mycat库的tbl_mycat_child配置为关联表, 分片列名为id, 父表为tbl_mycat, 则需要在shard_rules中添加以下配置:

{
    "db": "db_mycat",
    "table": "tbl_mycat_child",
    "type": "linked",
    "parent_table": "tbl_mycat",
    "key": "id"
}
此时即可执行分片内的关联查询:

SELECT * FROM tbl_mycat, tbl_mycat_child WHERE tbl_mycat_child.id=5 AND tbl_mycat.user_name='hello';
全局表
全局表是在各个slice上 (准确的说是各个slice的各个DB上) 数据完全一致的表, 方便执行一些跨分片查询, 配置如下:

{
    "db": "db_mycat",
    "table": "tbl_mycat_global",
    "type": "global",
    "locations": [
        2,
        2
    ],
    "slices": [
        "slice-0",
        "slice-1"
    ],
    "databases": [
        "db_mycat_[0-3]"
    ]
}

**Comment by chenshengfu** [comment]
全局表已配置测试没问题；
关联表有点没明白，{
"db": "db_mycat",
"table": "tbl_mycat_child",
"type": "linked",
"parent_table": "tbl_mycat",
"key": "id"
}
这个tbl_mycat就是我说的普通单表吗？然后还要手动创建一张和tbl_mycal结构一样的tbl_mycat_child是吧？

**Comment by lulufeiacount** [comment]
> 全局表已配置测试没问题； 关联表有点没明白，{ "db": "db_mycat", "table": "tbl_mycat_child", "type": "linked", "parent_table": "tbl_mycat", "key": "id" } 这个tbl_mycat就是我说的普通单表吗？然后还要手动创建一张和tbl_mycal结构一样的tbl_mycat_child是吧？

关联表其实也是分片表的一种形式，比如这个配置 `tbl_mycat_child`为 `tbl_mycat`的关联表，`tbl_mycat_child` 的分片规则与 `tbl_mycat` 一致，这样在进行两表关联查询时候，能够保证相同关联key的数据在同一个节点上，不会进行跨库查询。

**Comment by chenshengfu** [comment]
我测试了一下，好像同一个库同一种规则的两个分表的表也不能直接进行join操作，select b.* from enter_record as a left join out_record as b  on a.ParkId=b.ParkId; 提示check route result error, db: , table: park_out_record, err: check db and table error

**Comment by lulufeiacount** [comment]
> 我测试了一下，好像同一个库同一种规则的两个分表的表也不能直接进行join操作，select b.* from enter_record as a left join out_record as b on a.ParkId=b.ParkId; 提示check route result error, db: , table: park_out_record, err: check db and table error

配置文件有问题吧，分片配置发一下

**Comment by chenshengfu** [comment]
"shard_rules": [
        {
            "db": "testdb",
            "table": "enter_record",
            "type": "hash",
            "key": "id",
            "locations": [
                6
            ],
            "slices": [
                "slice-0"
            ]
        },
        {
            "db": "testdb",
            "table": "out_record",
            "type": "hash",
            "key": "id",
            "locations": [
                6
            ],
            "slices": [
                "slice-0"
            ]
        }
    ],

**Comment by lulufeiacount** [comment]
> 就一个数据库，然后这两个表，都分了6张子表 "slices": [ { "name": "slice-0", "user_name": "root", "password": "123456", "master": "192.168.10.1:3306", "slaves": null, "statistic_slaves": null, "capacity": 12, "max_capacity": 24, "idle_timeout": 60 } ], "shard_rules": [ { "db": "testdb", "table": "enter_record", "type": "hash", "key": "id", "locations": [ 6 ], "slices": [ "slice-0" ] }, { "db": "testdb", "table": "out_record", "type": "hash", "key": "id", "locations": [ 6 ], "slices": [ "slice-0" ] } ],

必须要把两张表配成关联表的分片规则，两张分片表才能进行关联查询

**Comment by chenshengfu** [comment]
配置成关联表的那个例子太简单了很难明白在哪配，我下面的配置，直接报错，可以提供一个比较完整的配置的demo吗？
"shard_rules": [
        {
            "db": "testdb",
            "table": "enter_record",
            "type": "hash",
            "key": "id",
            "locations": [
                6
            ],
            "slices": [
                "slice-0"
            ]
        },
        {
            "db": "testdb",
            "table": "out_record",
            "type": "hash",
            "key": "id",
            "locations": [
                6
            ],
            "slices": [
                "slice-0"
            ]
        },
        {
            "db": "testdb",
            "table": "enter_record",
            "type": "linked",
            "parent_table": "out_record",
            "key": "id"
        },
        {
            "db": "testdb",
            "table": "enter_record",
            "type": "linked",
            "parent_table": "out_record",
            "key": "id"
        } 
],

**Comment by lulufeiacount** [comment]
> 配置成关联表的那个例子太简单了很难明白在哪配，我下面的配置，直接报错，可以提供一个比较完整的配置的demo吗？ "shard_rules": [ { "db": "testdb", "table": "enter_record", "type": "hash", "key": "id", "locations": [ 6 ], "slices": [ "slice-0" ] }, { "db": "testdb", "table": "out_record", "type": "hash", "key": "id", "locations": [ 6 ], "slices": [ "slice-0" ] }, { "db": "testdb", "table": "enter_record", "type": "linked", "parent_table": "out_record", "key": "id" }, { "db": "testdb", "table": "enter_record", "type": "linked", "parent_table": "out_record", "key": "id" } ],

```json
"shard_rules": [
    {
        "db": "testdb",
        "table": "enter_record",
        "type": "hash",
        "key": "id",
        "locations": [
            6
        ],
        "slices": [
            "slice-0"
        ]
    },
    {
        "db": "testdb",
        "table": "out_record",
        "type": "linked",
        "parent_table": "enter_record",
        "key": "id"
    }
]

```
试试这个

**Comment by chenshengfu** [comment]
你这样配置，测试了确实可以。
但是，理解不过来，为什么out_record这个不需要加如下配置
{
        "db": "testdb",
        "table": "out_record",
        "type": "hash",
        "key": "id",
        "locations": [
            6
        ],
        "slices": [
            "slice-0"
        ]
    },

**Comment by lulufeiacount** [comment]
> 你这样配置，测试了确实可以。 但是，理解不过来，为什么out_record这个不需要加如下配置 { "db": "testdb", "table": "out_record", "type": "hash", "key": "id", "locations": [ 6 ], "slices": [ "slice-0" ] },

有条件可以看一下代码，关联表配置以后实际上就是你发的这个配置，只不过还把两张分片表给关联起来了，可以用来联合查询

**Comment by chenshengfu** [comment]
好的，感谢大佬耐心指导！
