### ISSUE TITLE
单机数据库，事务嵌套执行失败

### ISSUE THREAD

**Issue by xieyuhua** [XiaoMi/Gaea#179]
session error SQL, namespace: tp5_center_namespace_1, sql: SAVEPOINT LEVEL1, cost: 0 ms, err: get plan error, db: test_azmbk_db, sql: SAVEPOINT LEVEL1, err: parse sql error, sql: SAVEPOINT LEVEL1, err: line 1 column 9 near "SAVEPOINT LEVEL1"

**Comment by xieyuhua** [comment]
orm底层用 savepoint 的策略，什么时候考虑支持 savepoint 的策略呀

**Comment by xiyangxixian** [comment]
这个还在开发中，可以先把 orm 的 savepoint 关掉

**Comment by xiyangxixian** [comment]
https://github.com/XiaoMi/Gaea/pull/181
