### ISSUE TITLE
RELEASE SAVEPOINT  没有支持吗？

### ISSUE THREAD

**Issue by xieyuhua** [XiaoMi/Gaea#182]
'SQLSTATE[HY000]: General error: 1105 unknown error: get plan error, 
	db: xxxxxx, 
	sql: RELEASE SAVEPOINT LEVEL1, err: parse sql error, 
	sql: RELEASE SAVEPOINT LEVEL1, err: line 1 column 7 near "RELEASE SAVEPOINT LEVEL1" 
	The SQL being executed was: RELEASE SAVEPOINT LEVEL1'

**Comment by xiyangxixian** [comment]
目前支持了 svaepoint 和 rollback  to savepoint

**Comment by xiyangxixian** [comment]
详见： https://github.com/XiaoMi/Gaea/pull/183
