### ISSUE TITLE
SAVEPOINT 问题

### ISSUE THREAD

**Issue by xieyuhua** [XiaoMi/Gaea#193]
'SQLSTATE[HY000]: General error: 1105 unknown error: get plan error, db: test_db, sql: SAVEPOINT LEVEL1, err: parse sql error, sql: SAVEPOINT LEVEL1, err: line 1 column 9 near "SAVEPOINT LEVEL1" 
The SQL being executed was: SAVEPOINT LEVEL1' 

![image](https://user-images.githubusercontent.com/29120060/149299938-2a03e91c-cd14-446c-8e59-1d40a41efed7.png)

**Comment by xiyangxixian** [comment]
请问一下是用的哪个版本呢

**Comment by xieyuhua** [comment]
最新编译的

**Comment by xiyangxixian** [comment]
已经修复 https://github.com/XiaoMi/Gaea/pull/209
