### ISSUE TITLE
连接不上13306

### ISSUE THREAD

**Issue by wandagao** [XiaoMi/Gaea#205]
mysql -uroot -p -P13306 -h127.0.0.1
用mysql 本身 root 密码连接，连接不上

ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1:52746' (using password: Yes)
这个端口会不断变化

**Comment by lulufeiacount** [comment]
`ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1:52746' (using password: Yes)`
这个报错的端口是客户端接入13306的端口，可能是会变化的
目前从报错内容来看是root用户的密码错误，或者是root用户不存在，可以确认一下相关的用户是否配置正确

**Comment by wandagao** [comment]
> `ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1:52746' (using password: Yes)` 这个报错的端口是客户端接入13306的端口，可能是会变化的 目前从报错内容来看是root用户的密码错误，或者是root用户不存在，可以确认一下相关的用户是否配置正确

root用户就是本身登陆mysql的root 用户，是可以登陆3306的，但是无法透过proxy连

**Comment by lulufeiacount** [comment]
> > `ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1:52746' (using password: Yes)` 这个报错的端口是客户端接入13306的端口，可能是会变化的 目前从报错内容来看是root用户的密码错误，或者是root用户不存在，可以确认一下相关的用户是否配置正确
> 
> root用户就是本身登陆mysql的root 用户，是可以登陆3306的，但是无法透过proxy连

正常啊，你通过13306连接的话，是接入的gaea，用户名和密码得是gaea配置的用户名和密码，然后gaea再通过你配置的数据库的用户名和密码接入对应的数据库。这里涉及到两个用户名和密码是不一样的

**Comment by wandagao** [comment]
> > > `ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1:52746' (using password: Yes)` 这个报错的端口是客户端接入13306的端口，可能是会变化的 目前从报错内容来看是root用户的密码错误，或者是root用户不存在，可以确认一下相关的用户是否配置正确
> > 
> > 
> > root用户就是本身登陆mysql的root 用户，是可以登陆3306的，但是无法透过proxy连
> 
> 正常啊，你通过13306连接的话，是接入的gaea，用户名和密码得是gaea配置的用户名和密码，然后gaea再通过你配置的数据库的用户名和密码接入对应的数据库。这里涉及到两个用户名和密码是不一样的

这个您说的配置用户，是在namespace里面的对吗？这个我有配置，但是好像并没有导入etcd, 请问这个是怎么确认是否有导入，还有正确的导入方式是？

**Comment by lulufeiacount** [comment]
不一定非要导入etcd的，gaea也支持文件启动的。

**Comment by wandagao** [comment]
> 不一定非要导入etcd的，gaea也支持文件启动的。

嗯 file是可以的，但是可以请教一下etcd是怎么导入的吗，我应该是哪里弄错了，所以namespace没有导入

**Comment by lulufeiacount** [comment]
建议在etcd主机上装一个etcdkeeper直接网页端命令行操作。

**Comment by lulufeiacount** [comment]
ps:  gaea对于etcd的v2和v3接口有区分，默认好像是支持v2接口
