### ISSUE TITLE
Gaea分库分表环境下不兼容 order by max(clo) 

### ISSUE THREAD

**Issue by ximenluffy** [XiaoMi/Gaea#208]
`select col1 from t1 WHERE clo2 in ('xxx') and clo3 in (1) group by clo1 order by max(clo4) desc limit 0, 20;
ERROR 1105 (HY000): unknown error: get plan error, db: db1, sql: select clo1 from t1 WHERE clo2 in ('xxx') and clo3 in (1) group by clo1 order by max(clo4) desc limit 0, 20, err: create select plan error: handle OrderBy error: get order by fields error: ByItem.Expr is not a ColumnNameExpr`

**Comment by xiyangxixian** [comment]
supported by 2.4.2
