### ISSUE TITLE
使用java 8.0版本的driver连接gaea，后端mysql版本低于5.7.20时，报Unknown system variable 'transaction_isolation'

### ISSUE THREAD

**Issue by wangxj1986** [XiaoMi/Gaea#225]
java驱动版本：mysql-connector-java-8.0.11.jar
mysql版本：5.7.11
报错：java.sql.SQLException: Unknown system variable 'transaction_isolation'

初步判断是mysql版本问题，隔离级别参数说明：

> Note
> transaction_isolation was added in MySQL 5.7.20 as a synonym for tx_isolation, which is now deprecated and is removed in MySQL 8.0. Applications should be adjusted to use transaction_isolation in preference to tx_isolation.

MySQL 5.7.11中的确不支持这个参数：
```
mysql> select version();
+--------------+
| version()    |
+--------------+
| 5.7.11-4-log |
+--------------+
1 row in set (0.00 sec)

mysql> set transaction_isolation='READ-COMMITTED';
ERROR 1193 (HY000): Unknown system variable 'transaction_isolation'
```

但是同样的driver直连mysql不报错，即使mysql版本不支持transaction_isolation。

另外，测试其他版本的driver，则不报错，如：mysql-connector-java-6.0.5.jar

综上：触发报错的条件是：
1. driver 版本是8.0
2. mysql 版本低于5.7.20

**Comment by xiyangxixian** [comment]
fixed
