### ISSUE TITLE
HASH模式的分表，扩容的时候必须要迁移数据库才可以吗

### ISSUE THREAD

**Issue by xdkaka** [XiaoMi/Gaea#231]
比如当前连接的服务器数据库满了，需要增加新服务器的数据库，这个时候必须将旧数据重新手动分配到新数据库吗

**Comment by eastfisher** [comment]
需要重新调整分片表的配置, 如果是Range类的路由规则相对比较好处理, 增加新的Range即可, 如果是Hash类的路由规则, 需要将旧数据rehash到新的库表 (这个Rehash过程需要全程禁止写入), 然后调整Gaea namespace配置, 触发配置热更新.

**Comment by xdkaka** [comment]
> 



> 需要重新调整分片表的配置, 如果是Range类的路由规则相对比较好处理, 增加新的Range即可, 如果是Hash类的路由规则, 需要将旧数据rehash到新的库表 (这个Rehash过程需要全程禁止写入), 然后调整Gaea namespace配置, 触发配置热更新.

收到，感谢

**Comment by xdkaka** [comment]
您好，还有两个问题求助，非常感谢：
1、Range类的路由不用做数据迁移，是不是仅限于data时间类型的range，比如kingshard的range类型同样需要迁移数据，只要locations参数更改就必然涉及到数据库的迁移（rehash）呢？
2、如果做分库分表的升级，帮忙看下是不是要做的过程？

比如

刚开始设计成两个slice
locations为[2,2]
slice[0]中的表为 xxx_0000，xxx_0001
slice[1]中的表为 xxx_0002，xxx_0003

数据多了之后，需要分更多的表
locations变更为[4,4]
slice[0]中的表变更为 xxx_0000，xxx_0001，xxx_0002，xxx_0003
slice[1]中的表变更为 xxx_0004，xxx_0005，xxx_0006，xxx_0007

过了一阵，数据更多了之后，需要分更多的库
locations变更为[4,4,4]
slice[0]中的表变更为 xxx_0000，xxx_0001，xxx_0002，xxx_0003
slice[1]中的表变更为 xxx_0004，xxx_0005，xxx_0006，xxx_0007
slice[2]中的表变更为 xxx_0008，xxx_0009，xxx_0010，xxx_0011

升级涉及到三个地方的变更
1、变更表名+增加新表+增加新库
2、迁移数据（rehash）
3、更改配置
