### ISSUE TITLE
不支持多语句插入数据吗 

### ISSUE THREAD

**Issue by zpl06468** [XiaoMi/Gaea#256]
INSERT INTO `leo_test1`.`table_01` (`id`, `name`) VALUES (8, 'lisi');INSERT INTO `leo_test1`.`table_01` (`id`, `name`) VALUES (9, 'wangwu');
使用jdbc 
 PreparedStatement preparedStatement = connection.prepareStatement(sql2);
            ResultSet resultSet = preparedStatement.executeQuery();
执行上面语句报语法错误

**Comment by xiyangxixian** [comment]
目前这个版本是不支持的，需要修改 capability 的值

**Comment by zpl06468** [comment]
麻烦问下 怎么改

**Comment by xiyangxixian** [comment]
这个暂时还无法通过修改配置来解决，需要修改代码，这块比较复杂，可以参考未合并的 muti-query 的 mr

**Comment by zpl06468** [comment]
好像navicat上是可以的 是什么原因知道吗

**Comment by xiyangxixian** [comment]
navicat 上实际还是拆分成多条语句去执行多次这样

**Comment by zpl06468** [comment]
好的 感谢
