### ISSUE TITLE
测试发现Gaea不支持delete语句中的别名操作

### ISSUE THREAD

**Issue by lulufeiacount** [XiaoMi/Gaea#273]
测试发现Gaea不支持delete语句中的别名操作，MySQL8.0.16版本开始支持单表删除别名语法，Gaea测试会报语法错误，能不能兼容呢？

![image](https://github.com/user-attachments/assets/0320acba-bf91-4f83-9d99-d7e476567220)

**Comment by xiyangxixian** [comment]
这个测试方法走的是 parser 的逻辑，没有分库分表的情况下，现在执行逻辑不走 parser 了，上述 SQL 是可以执行的

**Comment by lulufeiacount** [comment]
就是分库分表场景下需要执行删除SQL中带别名的情况，我去看了目前最新的tidb-parser是支持此语法的，不知道Gaea这边何时兼容一下

**Comment by gongna-au** [comment]
非常感谢您提出该Issue,经过内部讨论，我们已经决定在 2.4.4 版本支持该语法🌹（到时候会同步Release Github

**Comment by lulufeiacount** [comment]
好的，感谢
