### ISSUE TITLE
最新版本(v2.4.2)是不是没发布？

### ISSUE THREAD

**Issue by ryeLearnMore** [XiaoMi/Gaea#275]
<img width="545" alt="image" src="https://github.com/user-attachments/assets/d53c27d4-9ee9-48d5-8778-8e2ebef278fc">
想引用v2.4.2发现无法引用，在上面也没有找到。是我哪里操作错了嘛？

**Comment by xiyangxixian** [comment]
2.4.2 已经发布了，tag 已经打出来了：
https://github.com/XiaoMi/Gaea/tree/v2.4.2
https://github.com/XiaoMi/Gaea/tags

**Comment by ryeLearnMore** [comment]
提个小建议哈。如果想引用v2版本以上，Go 的模块版本管理系统对 v2 及以上版本的处理要求特别严格。需要定义模块路径为：github.com/XiaoMi/Gaea/v2，否则无法直接通过 v2.4.2 版本号来引用。只能通过hash的方式引用

**Comment by gongna-au** [comment]
感谢您的建议，我们下次发版的时候会注意同步module github.com/XiaoMi/Gaea——> module github.com/XiaoMi/Gaea/v2🌹
