### ISSUE TITLE
监控模块生成每个时段的火焰图能分享下吗?

### ISSUE THREAD

**Issue by vicsoulz** [XiaoMi/Gaea#37]
之前在gopher上看到了监控那块,能查看每个时段的火焰图?是定时把profile存下来吗?能分享下吗?

**Comment by eastfisher** [comment]
不是火焰图, 是grafana监控面板, 监控数据存储使用prometheus.

**Comment by vicsoulz** [comment]
> 不是火焰图, 是grafana监控面板, 监控数据存储使用prometheus.
grafana监控面板上面的这块: 
![image](https://user-images.githubusercontent.com/17488687/60478967-cc796700-9cb6-11e9-9240-88a4f8045a36.png)

**Comment by eastfisher** [comment]
gaea-proxy暴露了pprof的http接口, 提供监控数据
