### ISSUE TITLE
什么时候能支持mysql8客户端？

### ISSUE THREAD

**Issue by ghost** [XiaoMi/Gaea#38]
mysql8客户端访问：
1. 密码验证阶段会失败。
2. utf8mb4还缺少不少collation配置

**Comment by endink** [comment]
我们自己拉了一份代码，已经支持了 mysql 8， 由于是自己用的魔改版本，底层日志库用 zap 替换了，无法 PR 给官方了， 但是代码可以参考

**Comment by xiyangxixian** [comment]
https://github.com/XiaoMi/Gaea/pull/174
