### ISSUE TITLE
jetbrain DataGrip connect error

### ISSUE THREAD

**Issue by dwdcth** [XiaoMi/Gaea#44]
Connection to @xxx.xxx.xx.xx failed.
[08001] Could not create connection to database server. Attempted reconnect 3 times. Giving up.
使用mysql自带客户端和Navicat连接没问题，经过测试发现使用jdbc mysql-connector 5.1的驱动可以，最新的8.0不行

**Comment by eastfisher** [comment]
可以提供一下mysql客户端的版本吗?

**Comment by dwdcth** [comment]
mysql客户端  5.7.27

**Comment by eastfisher** [comment]
目前还没有兼容MySQL 8新的认证方式
