### ISSUE TITLE
gaea-cc在配置两阶段提交时，没考虑proxy返回的错误信息，可能会导致proxy进程崩溃。

### ISSUE THREAD

**Issue by minxinqing** [XiaoMi/Gaea#95]
gaea-cc在配置两阶段提交时，请求 `/api/proxy/config/prepare/:namespace` 接口后，没有判断接口返回的内容，只判断了请求是否成功，接着直接去请求了`/api/proxy/config/commit/:namespace`接口，在以下情况会导致proxy进程崩溃。

如提交一个不存在的分片类型，`prepare`接口会报 “err: unknown rule type”，但是cc忽略了这个错误直接去请求 `commit`接口后，proxy通过`ReloadNamespaceCommit`方法把 `Manager.switchIndex`置为1，此时 `Manager.namespaces`下标1为nil（因为prepare接口并没有解析成功刚刚提交的错误分片类型namespace配置），导致`Manager.startConnectPoolMetricsTask()`方法中的这行代码`for nameSpaceName, _ := range m.namespaces[current].namespaces `引发错误"invalid memory address or nil pointer dereference"。

**Comment by xiaoxiaomaidoudou** [comment]
您好,gaea-cc在prepare之前会调用namespace.Verify()检查配置, 如果提交不存在的分片类型,会在verify阶段返回错误,prepare和commit不会继续进行.

**Comment by xiaoxiaomaidoudou** [comment]
您的gaea-cc使用的是什么版本的呢

**Comment by minxinqing** [comment]
> 您的gaea-cc使用的是什么版本的呢

尴尬，用的shazam，自定义了分片类型；刚看了下gaea的代码，的确有verify动作（shazam的verify是空的），在这个场景下不会有问题，但不考虑prepare接口的结果还是会有风险的。

**Comment by minxinqing** [comment]
我们现在是有几个项目都用shazam作为分片中间件，有的项目要自定义新的分片规则，就需要做二次开发，但是之前的项目因为用不到新的分片规则，所以就想不更新proxy，但是cc用的都是同一个，好管理，昨天测试的时候就发现这个二段提交的问题，老的proxy在接收cc提交的新分片规则请求的时候导致进程崩溃。

**Comment by xiaoxiaomaidoudou** [comment]
嗯嗯, 处理prepare接口返回错误确实非常有必要,这样即使没有verify或者各proxy不一致的情况都可以兼容, 感谢您的建议!
