### ISSUE TITLE
Gaea支持类似于Kingshard中的强制读主库功能吗?

### ISSUE THREAD

**Issue by neters** [XiaoMi/Gaea#99]
在对数据一致性要求比较高的场景下,kingshard的强制读主库功能还是很有用的,不知道Gaea是否有此功能

**Comment by eastfisher** [comment]
您好, 有3种方式可以实现强制读主库:

- 在SQL前面加上 /*master*/ 注释
- 配置账号为非读写分离 (rw_split=0)
- 开启事务
